version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_book2
    environment:
      POSTGRES_USER: Anastasia
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: book2
    ports:
      - "5430:5432"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
    restart: unless-stopped

  app:
    container_name: book
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5430/book2
      - SPRING_DATASOURCE_USERNAME=Anastasia
      - SPRING_DATASOURCE_PASSWORD=123456
      - SERVER_PORT=6305
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "6305:6305"
    depends_on:
      - postgres
